apiVersion: v1
kind: Service
metadata:
  name: pms-service
spec:
  type: NodePort      # Added missing service type
  ports:
  - port: 8082        # Combined fields into a single list item
    targetPort: 8082  # Target container port
    nodePort: 30007   # External port exposed on nodes
  selector:
    app: pms
