apiVersion: v1
kind: Secret
metadata:
  name: pms-secret
type: Opaque # Explicitly defines this as a standard generic secret
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA== # Decodes to "root"
  SPRING_DATASOURCE_PASSWORD: cnBzQDEyMzQ1 
